// FarmaGlass · productos reales de farmacia y cosmética para el catálogo del prototipo.
// Fuente: catálogo público de Farmacity (API VTEX /api/catalog_system/pub/products/search).
// Precios al 01/10/2026: "listPrice" es el precio de lista y "price" el precio final con la oferta vigente.
// Las imágenes se cargan desde el CDN de la tienda y pertenecen a sus marcas. Los nombres se ordenaron como
// "Marca producto (tamaño)" y las descripciones están escritas para el prototipo.
// Solo productos de venta libre que no son medicamentos: dermocosmética, cuidado personal, bebés,
// suplementos dietarios y botiquín. "fcId" es el id del producto en Farmacity y "pharmacy", la farmacia
// de la red que lo despacha. Para actualizar precios e imágenes: node scripts/actualizar-productos.js
window.FG_REAL_PRODUCTS = [
    { id: 11, fcId: 2489, name: 'La Roche-Posay Effaclar gel purificante (200 ml)', brand: 'La Roche-Posay', listPrice: 75162, price: 45097, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Gel de limpieza para piel mixta a grasa: limpia, purifica y ayuda a regular el sebo sin resecar.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/246641-500-500' },
    { id: 12, fcId: 248801, name: 'CeraVe crema hidratante intensiva (236 ml)', brand: 'CeraVe', listPrice: 47563, price: 28538, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Crema con 3 ceramidas esenciales y ácido hialurónico que hidrata y ayuda a reparar la barrera de la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/288607-500-500' },
    { id: 13, fcId: 243779, name: 'CeraVe agua micelar limpiadora (295 ml)', brand: 'CeraVe', listPrice: 47355, price: 28413, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Limpia y desmaquilla sin enjuague, con ceramidas para no resecar la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/264268-500-500' },
    { id: 14, fcId: 249137, name: 'Vichy Mineral 89 crema hidratante (40 ml)', brand: 'Vichy', listPrice: 76966, price: 46180, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Crema liviana con agua volcánica mineralizante y ácido hialurónico que fortalece la barrera de la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/292397-500-500' },
    { id: 15, fcId: 240160, name: 'Eucerin DermatoClean gel de limpieza facial (200 ml)', brand: 'Eucerin', listPrice: 55954, price: 39168, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Limpiador facial suave que retira impurezas, maquillaje y exceso de grasa. Apto para piel sensible.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/293860-500-500' },
    { id: 16, fcId: 206596, name: 'ISDIN solución micelar (400 ml)', brand: 'ISDIN', listPrice: 87135, price: 60994, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Agua micelar hidratante para todo tipo de piel: desmaquilla rostro y ojos sin enjuague.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/184235-500-500' },
    { id: 17, fcId: 245670, name: 'Bioderma Hydrabio Hyalu+ sérum (30 ml)', brand: 'Bioderma', listPrice: 119990, price: 71994, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Sérum con ácido hialurónico para pieles deshidratadas y sensibles.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/287456-500-500' },
    { id: 18, fcId: 2029, name: 'Avène agua termal (150 ml)', brand: 'Avène', listPrice: 47000, price: 47000, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Agua termal en spray que calma y suaviza la piel sensible o irritada.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/300701-500-500' },
    { id: 19, fcId: 249342, name: 'Dermaglós sérum retinol (25 ml)', brand: 'Dermaglós', listPrice: 54016, price: 32410, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'centro', flash: true, sale: 'Venta libre', desc: 'Sérum facial con retinol que atenúa las líneas de expresión y mejora la textura de la piel. De uso nocturno.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/292741-500-500' },
    { id: 20, fcId: 243996, name: 'Neutrogena Hydro Boost sérum antimanchas (30 ml)', brand: 'Neutrogena', listPrice: 41270, price: 30952, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Sérum con 10 % de niacinamida y ácido hialurónico que hidrata y ayuda a unificar el tono.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/274460-500-500' },
    { id: 21, fcId: 240628, name: 'Nivea Q10 sérum antiarrugas Expert (30 ml)', brand: 'Nivea', listPrice: 41938, price: 20969, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Sérum facial de doble acción con coenzima Q10 para reducir las arrugas y prevenir nuevas.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/257888-500-500' },
    { id: 22, fcId: 240850, name: 'La Roche-Posay Anthelios leche infantil FPS 50+ (250 ml)', brand: 'La Roche-Posay', listPrice: 93323, price: 55994, cat: 'Protección solar', categories: ['dermocosmetica', 'bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Protector solar corporal dermopediátrico de muy alta protección, para la piel sensible de los chicos.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/258315-500-500' },
    { id: 23, fcId: 4644, name: 'Dermaglós protector solar FPS 80 (90 g)', brand: 'Dermaglós', listPrice: 36678, price: 29342, cat: 'Protección solar', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Protección muy alta para piel extremadamente sensible. Resistente al agua.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/247585-500-500' },
    { id: 24, fcId: 4763, name: 'Elvive Óleo Extraordinario (100 ml)', brand: 'L\'Oréal Paris Elvive', listPrice: 21990, price: 13194, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Óleo capilar que nutre el pelo seco y le da brillo sin dejarlo pesado.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/230686-500-500' },
    { id: 25, fcId: 484, name: 'Dove acondicionador Óleo Nutrición (400 ml)', brand: 'Dove', listPrice: 11298, price: 6779, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Acondicionador con óleos nutritivos para pelo seco. Combina con la máscara Dove Óleo Nutrición.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/293631-500-500' },
    { id: 26, fcId: 249574, name: 'Head & Shoulders shampoo romero anticaída (375 ml)', brand: 'Head & Shoulders', listPrice: 13032, price: 9122, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Shampoo anticaspa con romero que ayuda a reducir la caída del pelo por quiebre.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/290617-500-500' },
    { id: 27, fcId: 1989, name: 'Nivea Soft crema hidratante intensiva (200 ml)', brand: 'Nivea', listPrice: 10670, price: 10670, cat: 'Cuidado personal', categories: ['cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Crema liviana para rostro, manos y cuerpo, de rápida absorción.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/273073-500-500' },
    { id: 28, fcId: 1459, name: 'Listerine Antisarro enjuague bucal (500 ml)', brand: 'Listerine', listPrice: 9739, price: 7304, cat: 'Cuidado oral', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Enjuague bucal con zinc que ayuda a prevenir la formación de sarro.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/268875-500-500' },
    { id: 29, fcId: 246313, name: 'Oral-B Indicator cepillo dental suave (x4)', brand: 'Oral-B', listPrice: 17388, price: 11302, cat: 'Cuidado oral', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Pack familiar de 4 cepillos de cerdas suaves con indicador de recambio.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/280669-500-500' },
    { id: 30, fcId: 251709, name: 'Rexona Women Invisible antitranspirante (150 ml)', brand: 'Rexona', listPrice: 8003, price: 5202, cat: 'Cuidado personal', categories: ['cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Desodorante antitranspirante en aerosol que no deja marcas en la ropa.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/297446-500-500' },
    { id: 31, fcId: 244525, name: 'Huggies toallitas húmedas Limpieza Diaria (x112)', brand: 'Huggies', listPrice: 9850, price: 9850, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Toallitas con pH balanceado para el cambio de pañal, testeadas dermatológicamente.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/268022-500-500' },
    { id: 32, fcId: 212320, name: 'Hipoglós crema Cuidado Diario (90 g)', brand: 'Hipoglós', listPrice: 30857, price: 23143, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Crema para prevenir las paspaduras en cada cambio de pañal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/217196-500-500' },
    { id: 33, fcId: 244406, name: 'Johnson\'s Baby Derma Protect jabón líquido (200 ml)', brand: 'Johnson\'s', listPrice: 14268, price: 8561, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'parque', flash: true, sale: 'Venta libre', desc: 'Jabón líquido nutritivo que limpia cuidando la barrera de la piel del bebé.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/267133-500-500' },
    { id: 34, fcId: 220649, name: 'OFF! Defense Bebé gel repelente (100 ml)', brand: 'OFF!', listPrice: 19239, price: 14429, cat: 'Bebés y maternidad', categories: ['bebes', 'farmacia'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Gel repelente de mosquitos con icaridina, apto para bebés desde los 3 meses.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/228351-500-500' },
    { id: 35, fcId: 227712, name: 'Ensure Advance sabor café (220 ml)', brand: 'Ensure', listPrice: 20038, price: 13025, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento nutricional)', desc: 'Suplemento nutricional listo para tomar, con proteínas que ayudan a mantener la masa muscular.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/221843-500-500' },
    { id: 36, fcId: 224706, name: 'Centrum Adulto multivitamínico (30 comp.)', brand: 'Centrum', listPrice: 18207, price: 18207, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario con vitaminas y minerales para el día a día.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/260728-500-500' },
    { id: 37, fcId: 242375, name: 'Redoxon Triple Acción (30 comp.)', brand: 'Redoxon', listPrice: 19770, price: 19770, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario con vitamina C, vitamina D y zinc.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/261965-500-500' },
    { id: 38, fcId: 246568, name: 'Supradyn Magnesio 200 mg (30 comp.)', brand: 'Supradyn', listPrice: 17645, price: 17645, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario de magnesio que acompaña el rendimiento muscular.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/281581-500-500' },
    { id: 39, fcId: 249889, name: 'Simple colágeno hidrolizado sabor limonada (273 g)', brand: 'Simple', listPrice: 38966, price: 31173, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Colágeno hidrolizado en polvo sabor limonada, para preparar en agua.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/291816-500-500' },
    { id: 40, fcId: 245124, name: 'Coronet termómetro clínico de galio', brand: 'Coronet', listPrice: 9921, price: 9921, cat: 'Farmacia y botiquín', categories: ['farmacia'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Termómetro clínico libre de mercurio para medir la temperatura corporal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/274764-500-500' },
    { id: 41, fcId: 219857, name: 'Curitas Marvel apósitos para niños (x20)', brand: 'Curitas', listPrice: 5141, price: 4113, cat: 'Farmacia y botiquín', categories: ['farmacia', 'bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Apósitos adhesivos con personajes de Marvel para heridas pequeñas.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/256543-500-500' },
    { id: 42, fcId: 219697, name: 'Aseplus alcohol en gel (500 ml)', brand: 'Aseplus', listPrice: 8129, price: 8129, cat: 'Higiene y desinfección', categories: ['farmacia', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Alcohol en gel antibacterial para manos, de uso tópico.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/205951-500-500' },
    { id: 43, fcId: 229414, name: 'OFF! Extra Duración repelente aerosol (170 g)', brand: 'OFF!', listPrice: 13158, price: 9868, cat: 'Farmacia y botiquín', categories: ['farmacia', 'cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Repelente de mosquitos en aerosol de larga duración, para actividades al aire libre.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/227201-500-500' },
    { id: 44, fcId: 5105, name: 'Espadol Dettol jabón líquido antibacterial (250 ml)', brand: 'Espadol', listPrice: 6588, price: 6588, cat: 'Higiene y desinfección', categories: ['farmacia', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Jabón líquido cremoso antibacterial con dosificador.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/263132-500-500' },
];

// Línea propia de cada farmacia (ids 101–124): también son productos reales de Farmacity, con los mismos
// datos y el mismo script de actualización. Reemplazan a los productos dibujados del prototipo.
window.FG_STORE_LINE = [
    { id: 101, fcId: 5121, pharmacy: 'centro', name: 'Bushi crema de caléndula', size: '50 g', brand: 'Bushi', listPrice: 15241, price: 11431, desc: 'Crema de caléndula para pieles sensibles y agrietadas.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/264287-500-500' },
    { id: 102, fcId: 231461, pharmacy: 'centro', name: 'Veganis agua de rosas', size: '120 ml', brand: 'Veganis', listPrice: 15834, price: 15834, desc: 'Tónico facial de agua de rosas, refrescante y suave.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/232369-500-500' },
    { id: 103, fcId: 210108, pharmacy: 'centro', name: 'Rexona jabón de glicerina neutro', size: 'x3', brand: 'Rexona', listPrice: 5132, price: 5132, desc: 'Jabones de glicerina neutros, sin perfume fuerte.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/241645-500-500' },
    { id: 104, fcId: 62078, pharmacy: 'centro', name: 'Ewe vaselina sólida', size: '60 g', brand: 'Ewe', listPrice: 6147, price: 6147, desc: 'Vaselina pura para proteger e hidratar la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/206733-500-500' },
    { id: 117, fcId: 38299, pharmacy: 'centro', name: 'Ewe vaselina líquida extra densa', size: '250 ml', brand: 'Ewe', listPrice: 10528, price: 10528, desc: 'Vaselina líquida para masajes e hidratación corporal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/216717-500-500' },
    { id: 118, fcId: 219396, pharmacy: 'centro', name: 'Rexona Efficient talco', size: '200 g', brand: 'Rexona', listPrice: 6781, price: 6781, desc: 'Talco refrescante para pies y cuerpo.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/288176-500-500' },
    { id: 105, fcId: 227775, pharmacy: 'plaza', name: 'Garnier sérum iluminador vitamina C', size: '30 ml', brand: 'Garnier', listPrice: 41990, price: 41990, desc: 'Sérum con vitamina C para dar luminosidad a la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/287333-500-500' },
    { id: 106, fcId: 236797, pharmacy: 'plaza', name: 'Acf bruma reparadora centella asiática', size: '100 ml', brand: 'Acf by Dadatina', listPrice: 26200, price: 26200, desc: 'Bruma calmante con centella asiática para pieles con granitos.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/274322-500-500' },
    { id: 107, fcId: 231709, pharmacy: 'plaza', name: 'Acf protector labial FPS 35', size: '1 g', brand: 'Acf by Dadatina', listPrice: 14900, price: 14900, desc: 'Protector labial con color y protección solar.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/269675-500-500' },
    { id: 108, fcId: 248198, pharmacy: 'plaza', name: 'Caviahue bruma facial Hidratermal', size: '75 ml', brand: 'Caviahue', listPrice: 35000, price: 24500, desc: 'Bruma con agua termal para refrescar e hidratar el rostro.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/292007-500-500' },
    { id: 119, fcId: 249286, pharmacy: 'plaza', name: 'Get The Look mascarilla Lumiglow', size: '1 u.', brand: 'Get The Look', listPrice: 4990, price: 4990, desc: 'Mascarilla facial de tela para una piel luminosa.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/297504-500-500' },
    { id: 120, fcId: 248788, pharmacy: 'plaza', name: 'Veganis contorno de ojos', size: '15 ml', brand: 'Veganis', listPrice: 21228, price: 21228, desc: 'Contorno de ojos vegano para descongestionar la mirada.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/288623-500-500' },
    { id: 109, fcId: 242107, pharmacy: 'norte', name: 'Magnesio 102 suplemento dietario', size: '30 comp.', brand: 'Magnesio 102', listPrice: 18351, price: 14681, desc: 'Suplemento dietario de magnesio.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/260745-500-500' },
    { id: 110, fcId: 232920, pharmacy: 'norte', name: 'Ultraflex colágeno hidrolizado', size: '15 sobres', brand: 'Ultraflex', listPrice: 27501, price: 20626, desc: 'Sobres de colágeno hidrolizado para articulaciones.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/239974-500-500' },
    { id: 111, fcId: 12193, pharmacy: 'norte', name: 'Artrosil gel árnica roll-on', size: '90 g', brand: 'Artrosil', listPrice: 15998, price: 15998, desc: 'Gel de árnica y andiroba de efecto frío para después del ejercicio.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/172477-500-500' },
    { id: 112, fcId: 211455, pharmacy: 'norte', name: 'Pure Wellness colágeno Flex', size: '339 g', brand: 'Pure Wellness', listPrice: 42800, price: 27820, desc: 'Suplemento dietario de colágeno en polvo.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/233377-500-500' },
    { id: 121, fcId: 230336, pharmacy: 'norte', name: 'On Roll Active gel corporal', size: '60 g', brand: 'On Roll', listPrice: 13500, price: 13500, desc: 'Gel corporal roll-on para músculos cansados.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/229587-500-500' },
    { id: 122, fcId: 244566, pharmacy: 'norte', name: 'Dermaglós Sport protector solar FPS 50', size: '100 ml', brand: 'Dermaglós', listPrice: 29012, price: 20308, desc: 'Protector solar resistente al agua y al sudor.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/269226-500-500' },
    { id: 113, fcId: 161060, pharmacy: 'parque', name: 'Aveno shampoo bebés y niños', size: '250 ml', brand: 'Aveno', listPrice: 32349, price: 24262, desc: 'Shampoo suave con avena para bebés y niños.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/241657-500-500' },
    { id: 114, fcId: 38308, pharmacy: 'parque', name: 'Ewe óleo calcáreo', size: '500 ml', brand: 'Ewe', listPrice: 15458, price: 15458, desc: 'Limpia y protege la zona del pañal en cada cambio.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/203632-500-500' },
    { id: 115, fcId: 7887, pharmacy: 'parque', name: 'Hipoglós crema protección contra paspaduras', size: '30 g', brand: 'Hipoglós', listPrice: 14275, price: 10706, desc: 'Crema que forma una barrera protectora contra las paspaduras.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/217197-500-500' },
    { id: 116, fcId: 9129, pharmacy: 'parque', name: 'Pampers toallitas Caricia de Bebé', size: 'x48', brand: 'Pampers', listPrice: 8869, price: 8869, desc: 'Toallitas húmedas suaves para el cambio de pañal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/293694-500-500' },
    { id: 123, fcId: 15030, pharmacy: 'parque', name: 'Repelente natural en crema con citronela', size: '70 g', brand: 'Citronela', listPrice: 9018, price: 9018, desc: 'Repelente natural apto para bebés y niños.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/166470-500-500' },
    { id: 124, fcId: 220677, pharmacy: 'parque', name: 'Protex jabón líquido avena', size: '221 ml', brand: 'Protex', listPrice: 5565, price: 5565, desc: 'Jabón líquido con avena para manos y cuerpo.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/208764-500-500' },
];
