// FarmaGlass · productos reales de farmacia y cosmética para el catálogo del prototipo.
// Fuente: catálogo público de Farmacity (API VTEX /api/catalog_system/pub/products/search).
// Precios al 01/10/2026: "listPrice" es el precio de lista y "price" el precio final con la oferta vigente.
// Las imágenes se cargan desde el CDN de la tienda y pertenecen a sus marcas. Los nombres se ordenaron como
// "Marca producto (tamaño)" y las descripciones están escritas para el prototipo.
// Solo productos de venta libre que no son medicamentos: dermocosmética, cuidado personal, bebés,
// suplementos dietarios y botiquín. "fcId" es el id del producto en Farmacity y "pharmacy", la farmacia
// de la red que lo despacha. Para actualizar precios e imágenes: node scripts/actualizar-productos.js
window.FG_REAL_PRODUCTS = [
    { id: 11, fcId: 2489, name: 'La Roche-Posay Effaclar gel purificante (200 ml)', brand: 'La Roche-Posay', listPrice: 75162, price: 45097, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Gel de limpieza para piel mixta a grasa: limpia, purifica y ayuda a regular el sebo sin resecar.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/246641-500-500' },
    { id: 12, fcId: 248801, name: 'CeraVe crema hidratante intensiva (236 ml)', brand: 'CeraVe', listPrice: 47563, price: 28538, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Crema con 3 ceramidas esenciales y ácido hialurónico que hidrata y ayuda a reparar la barrera de la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/288607-500-500' },
    { id: 13, fcId: 243779, name: 'CeraVe agua micelar limpiadora (295 ml)', brand: 'CeraVe', listPrice: 47355, price: 28413, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Limpia y desmaquilla sin enjuague, con ceramidas para no resecar la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/264268-500-500' },
    { id: 14, fcId: 249137, name: 'Vichy Mineral 89 crema hidratante (40 ml)', brand: 'Vichy', listPrice: 76966, price: 46180, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Crema liviana con agua volcánica mineralizante y ácido hialurónico que fortalece la barrera de la piel.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/292397-500-500' },
    { id: 15, fcId: 240160, name: 'Eucerin DermatoClean gel de limpieza facial (200 ml)', brand: 'Eucerin', listPrice: 55954, price: 39168, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Limpiador facial suave que retira impurezas, maquillaje y exceso de grasa. Apto para piel sensible.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/293860-500-500' },
    { id: 16, fcId: 206596, name: 'ISDIN solución micelar (400 ml)', brand: 'ISDIN', listPrice: 87135, price: 60994, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Agua micelar hidratante para todo tipo de piel: desmaquilla rostro y ojos sin enjuague.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/184235-500-500' },
    { id: 17, fcId: 245670, name: 'Bioderma Hydrabio Hyalu+ sérum (30 ml)', brand: 'Bioderma', listPrice: 119990, price: 71994, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Sérum con ácido hialurónico para pieles deshidratadas y sensibles.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/287456-500-500' },
    { id: 18, fcId: 2029, name: 'Avène agua termal (150 ml)', brand: 'Avène', listPrice: 47000, price: 47000, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Agua termal en spray que calma y suaviza la piel sensible o irritada.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/300701-500-500' },
    { id: 19, fcId: 249342, name: 'Dermaglós sérum retinol (25 ml)', brand: 'Dermaglós', listPrice: 54016, price: 32410, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'centro', flash: true, sale: 'Venta libre', desc: 'Sérum facial con retinol que atenúa las líneas de expresión y mejora la textura de la piel. De uso nocturno.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/292741-500-500' },
    { id: 20, fcId: 243996, name: 'Neutrogena Hydro Boost sérum antimanchas (30 ml)', brand: 'Neutrogena', listPrice: 41270, price: 30952, cat: 'Dermocosmética', categories: ['dermocosmetica'], pharmacy: 'plaza', sale: 'Venta libre', desc: 'Sérum con 10 % de niacinamida y ácido hialurónico que hidrata y ayuda a unificar el tono.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/274460-500-500' },
    { id: 21, fcId: 240628, name: 'Nivea Q10 sérum antiarrugas Expert (30 ml)', brand: 'Nivea', listPrice: 41938, price: 20969, cat: 'Dermocosmética', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Sérum facial de doble acción con coenzima Q10 para reducir las arrugas y prevenir nuevas.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/257888-500-500' },
    { id: 22, fcId: 240850, name: 'La Roche-Posay Anthelios leche infantil FPS 50+ (250 ml)', brand: 'La Roche-Posay', listPrice: 93323, price: 55994, cat: 'Protección solar', categories: ['dermocosmetica', 'bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Protector solar corporal dermopediátrico de muy alta protección, para la piel sensible de los chicos.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/258315-500-500' },
    { id: 23, fcId: 4644, name: 'Dermaglós protector solar FPS 80 (90 g)', brand: 'Dermaglós', listPrice: 36678, price: 29342, cat: 'Protección solar', categories: ['dermocosmetica', 'cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Protección muy alta para piel extremadamente sensible. Resistente al agua.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/247585-500-500' },
    { id: 24, fcId: 4763, name: 'Elvive Óleo Extraordinario (100 ml)', brand: 'L\'Oréal Paris Elvive', listPrice: 21990, price: 13194, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'plaza', flash: true, sale: 'Venta libre', desc: 'Óleo capilar que nutre el pelo seco y le da brillo sin dejarlo pesado.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/230686-500-500' },
    { id: 25, fcId: 484, name: 'Dove acondicionador Óleo Nutrición (400 ml)', brand: 'Dove', listPrice: 11298, price: 6779, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Acondicionador con óleos nutritivos para pelo seco. Combina con la máscara Dove Óleo Nutrición.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/293631-500-500' },
    { id: 26, fcId: 249574, name: 'Head & Shoulders shampoo romero anticaída (375 ml)', brand: 'Head & Shoulders', listPrice: 13032, price: 9122, cat: 'Cuidado capilar', categories: ['cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Shampoo anticaspa con romero que ayuda a reducir la caída del pelo por quiebre.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/290617-500-500' },
    { id: 27, fcId: 1989, name: 'Nivea Soft crema hidratante intensiva (200 ml)', brand: 'Nivea', listPrice: 10670, price: 10670, cat: 'Cuidado personal', categories: ['cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Crema liviana para rostro, manos y cuerpo, de rápida absorción.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/273073-500-500' },
    { id: 28, fcId: 1459, name: 'Listerine Antisarro enjuague bucal (500 ml)', brand: 'Listerine', listPrice: 9739, price: 7304, cat: 'Cuidado oral', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Enjuague bucal con zinc que ayuda a prevenir la formación de sarro.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/268875-500-500' },
    { id: 29, fcId: 246313, name: 'Oral-B Indicator cepillo dental suave (x4)', brand: 'Oral-B', listPrice: 17388, price: 11302, cat: 'Cuidado oral', categories: ['cuidado'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Pack familiar de 4 cepillos de cerdas suaves con indicador de recambio.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/280669-500-500' },
    { id: 30, fcId: 251709, name: 'Rexona Women Invisible antitranspirante (150 ml)', brand: 'Rexona', listPrice: 8003, price: 5202, cat: 'Cuidado personal', categories: ['cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Desodorante antitranspirante en aerosol que no deja marcas en la ropa.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/297446-500-500' },
    { id: 31, fcId: 244525, name: 'Huggies toallitas húmedas Limpieza Diaria (x112)', brand: 'Huggies', listPrice: 9850, price: 9850, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Toallitas con pH balanceado para el cambio de pañal, testeadas dermatológicamente.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/268022-500-500' },
    { id: 32, fcId: 212320, name: 'Hipoglós crema Cuidado Diario (90 g)', brand: 'Hipoglós', listPrice: 30857, price: 23143, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Crema para prevenir las paspaduras en cada cambio de pañal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/217196-500-500' },
    { id: 33, fcId: 244406, name: 'Johnson\'s Baby Derma Protect jabón líquido (200 ml)', brand: 'Johnson\'s', listPrice: 14268, price: 8561, cat: 'Bebés y maternidad', categories: ['bebes'], pharmacy: 'parque', flash: true, sale: 'Venta libre', desc: 'Jabón líquido nutritivo que limpia cuidando la barrera de la piel del bebé.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/267133-500-500' },
    { id: 34, fcId: 220649, name: 'OFF! Defense Bebé gel repelente (100 ml)', brand: 'OFF!', listPrice: 19239, price: 14429, cat: 'Bebés y maternidad', categories: ['bebes', 'farmacia'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Gel repelente de mosquitos con icaridina, apto para bebés desde los 3 meses.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/228351-500-500' },
    { id: 35, fcId: 227712, name: 'Ensure Advance sabor café (220 ml)', brand: 'Ensure', listPrice: 20038, price: 13025, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento nutricional)', desc: 'Suplemento nutricional listo para tomar, con proteínas que ayudan a mantener la masa muscular.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/221843-500-500' },
    { id: 36, fcId: 224706, name: 'Centrum Adulto multivitamínico (30 comp.)', brand: 'Centrum', listPrice: 18207, price: 18207, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario con vitaminas y minerales para el día a día.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/260728-500-500' },
    { id: 37, fcId: 242375, name: 'Redoxon Triple Acción (30 comp.)', brand: 'Redoxon', listPrice: 19770, price: 19770, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario con vitamina C, vitamina D y zinc.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/261965-500-500' },
    { id: 38, fcId: 246568, name: 'Supradyn Magnesio 200 mg (30 comp.)', brand: 'Supradyn', listPrice: 17645, price: 17645, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Suplemento dietario de magnesio que acompaña el rendimiento muscular.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/281581-500-500' },
    { id: 39, fcId: 249889, name: 'Simple colágeno hidrolizado sabor limonada (273 g)', brand: 'Simple', listPrice: 38966, price: 31173, cat: 'Nutrición y vitaminas', categories: ['nutricion'], pharmacy: 'norte', sale: 'Venta libre (suplemento dietario)', desc: 'Colágeno hidrolizado en polvo sabor limonada, para preparar en agua.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/291816-500-500' },
    { id: 40, fcId: 245124, name: 'Coronet termómetro clínico de galio', brand: 'Coronet', listPrice: 9921, price: 9921, cat: 'Farmacia y botiquín', categories: ['farmacia'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Termómetro clínico libre de mercurio para medir la temperatura corporal.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/274764-500-500' },
    { id: 41, fcId: 219857, name: 'Curitas Marvel apósitos para niños (x20)', brand: 'Curitas', listPrice: 5141, price: 4113, cat: 'Farmacia y botiquín', categories: ['farmacia', 'bebes'], pharmacy: 'parque', sale: 'Venta libre', desc: 'Apósitos adhesivos con personajes de Marvel para heridas pequeñas.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/256543-500-500' },
    { id: 42, fcId: 219697, name: 'Aseplus alcohol en gel (500 ml)', brand: 'Aseplus', listPrice: 8129, price: 8129, cat: 'Higiene y desinfección', categories: ['farmacia', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Alcohol en gel antibacterial para manos, de uso tópico.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/205951-500-500' },
    { id: 43, fcId: 229414, name: 'OFF! Extra Duración repelente aerosol (170 g)', brand: 'OFF!', listPrice: 13158, price: 9868, cat: 'Farmacia y botiquín', categories: ['farmacia', 'cuidado'], pharmacy: 'norte', sale: 'Venta libre', desc: 'Repelente de mosquitos en aerosol de larga duración, para actividades al aire libre.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/227201-500-500' },
    { id: 44, fcId: 5105, name: 'Espadol Dettol jabón líquido antibacterial (250 ml)', brand: 'Espadol', listPrice: 6588, price: 6588, cat: 'Higiene y desinfección', categories: ['farmacia', 'cuidado'], pharmacy: 'centro', sale: 'Venta libre', desc: 'Jabón líquido cremoso antibacterial con dosificador.', img: 'https://farmacityar.vtexassets.com/arquivos/ids/263132-500-500' },
];
